### ISSUE TITLE
[기능개선제안] 닉네임 빈 값 시 닉네임 입력 요청 처리 기능

### ISSUE THREAD

**Issue by subincdev** [qorlgns1/anonymous-lion-frontend#15]
## 제안할사항
닉네임 빈 값 시 닉네임 입력 요청 처리 기능

## 제안한 이유
닉네임이 빈 값일 경우에도 게시글이 작성되어, 닉네임 입력을 요쳥하는 기능이 필요할 것 같습니다.

## 추가적으로 논의할 사항
닉네임이 일정 글자수 이상이 되면 말줄임을 통해 보이지 않게되는데,
이 점이 개선되어야할 것 같습니다. 
닉네임의 글자수를 제한하거나, 속성을 통해 유저에게 
풀닉네임을 보이게 하는 기능이 있어야할 것 같습니다.
추후 논의해보면 좋을 것 같습니다 :-)

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네

**Comment by jsk3342** [comment]
고생하셨습니다.

**Comment by qorlgns1** [comment]
좋아요! 감사합니다!!
